//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace unigis.unigisData {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsGetGuiasSoap", Namespace="http://tempuri.org/")]
    public partial class wsGetGuias : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getGuiasOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateGuiaCargadaOperationCompleted;
        
        private System.Threading.SendOrPostCallback getNuevasParadasOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateParadaIdOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsGetGuias() {
            this.Url = global::unigis.Properties.Settings.Default.unigis_unigisData_wsGetGuias;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getGuiasCompletedEventHandler getGuiasCompleted;
        
        /// <remarks/>
        public event updateGuiaCargadaCompletedEventHandler updateGuiaCargadaCompleted;
        
        /// <remarks/>
        public event getNuevasParadasCompletedEventHandler getNuevasParadasCompleted;
        
        /// <remarks/>
        public event updateParadaIdCompletedEventHandler updateParadaIdCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getGuias", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getGuias(string date) {
            object[] results = this.Invoke("getGuias", new object[] {
                        date});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getGuiasAsync(string date) {
            this.getGuiasAsync(date, null);
        }
        
        /// <remarks/>
        public void getGuiasAsync(string date, object userState) {
            if ((this.getGuiasOperationCompleted == null)) {
                this.getGuiasOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetGuiasOperationCompleted);
            }
            this.InvokeAsync("getGuias", new object[] {
                        date}, this.getGuiasOperationCompleted, userState);
        }
        
        private void OngetGuiasOperationCompleted(object arg) {
            if ((this.getGuiasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getGuiasCompleted(this, new getGuiasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateGuiaCargada", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string updateGuiaCargada(string pGuia, string pGuid) {
            object[] results = this.Invoke("updateGuiaCargada", new object[] {
                        pGuia,
                        pGuid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void updateGuiaCargadaAsync(string pGuia, string pGuid) {
            this.updateGuiaCargadaAsync(pGuia, pGuid, null);
        }
        
        /// <remarks/>
        public void updateGuiaCargadaAsync(string pGuia, string pGuid, object userState) {
            if ((this.updateGuiaCargadaOperationCompleted == null)) {
                this.updateGuiaCargadaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateGuiaCargadaOperationCompleted);
            }
            this.InvokeAsync("updateGuiaCargada", new object[] {
                        pGuia,
                        pGuid}, this.updateGuiaCargadaOperationCompleted, userState);
        }
        
        private void OnupdateGuiaCargadaOperationCompleted(object arg) {
            if ((this.updateGuiaCargadaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateGuiaCargadaCompleted(this, new updateGuiaCargadaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getNuevasParadas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getNuevasParadas() {
            object[] results = this.Invoke("getNuevasParadas", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getNuevasParadasAsync() {
            this.getNuevasParadasAsync(null);
        }
        
        /// <remarks/>
        public void getNuevasParadasAsync(object userState) {
            if ((this.getNuevasParadasOperationCompleted == null)) {
                this.getNuevasParadasOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetNuevasParadasOperationCompleted);
            }
            this.InvokeAsync("getNuevasParadas", new object[0], this.getNuevasParadasOperationCompleted, userState);
        }
        
        private void OngetNuevasParadasOperationCompleted(object arg) {
            if ((this.getNuevasParadasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getNuevasParadasCompleted(this, new getNuevasParadasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateParadaId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string updateParadaId(string viajeId, string paradaId, string guia) {
            object[] results = this.Invoke("updateParadaId", new object[] {
                        viajeId,
                        paradaId,
                        guia});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void updateParadaIdAsync(string viajeId, string paradaId, string guia) {
            this.updateParadaIdAsync(viajeId, paradaId, guia, null);
        }
        
        /// <remarks/>
        public void updateParadaIdAsync(string viajeId, string paradaId, string guia, object userState) {
            if ((this.updateParadaIdOperationCompleted == null)) {
                this.updateParadaIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateParadaIdOperationCompleted);
            }
            this.InvokeAsync("updateParadaId", new object[] {
                        viajeId,
                        paradaId,
                        guia}, this.updateParadaIdOperationCompleted, userState);
        }
        
        private void OnupdateParadaIdOperationCompleted(object arg) {
            if ((this.updateParadaIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateParadaIdCompleted(this, new updateParadaIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getGuiasCompletedEventHandler(object sender, getGuiasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getGuiasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getGuiasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void updateGuiaCargadaCompletedEventHandler(object sender, updateGuiaCargadaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateGuiaCargadaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateGuiaCargadaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getNuevasParadasCompletedEventHandler(object sender, getNuevasParadasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getNuevasParadasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getNuevasParadasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void updateParadaIdCompletedEventHandler(object sender, updateParadaIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateParadaIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateParadaIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591