//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace unigis.unigisViajes {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsGetViajesSoap", Namespace="http://tempuri.org/")]
    public partial class wsGetViajes : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getViajesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getViajesCerradosOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateRutaIdOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsGetViajes() {
            this.Url = global::unigis.Properties.Settings.Default.unigis_unigisViajes_wsGetViajes;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getViajesCompletedEventHandler getViajesCompleted;
        
        /// <remarks/>
        public event getViajesCerradosCompletedEventHandler getViajesCerradosCompleted;
        
        /// <remarks/>
        public event updateRutaIdCompletedEventHandler updateRutaIdCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getViajes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getViajes() {
            object[] results = this.Invoke("getViajes", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getViajesAsync() {
            this.getViajesAsync(null);
        }
        
        /// <remarks/>
        public void getViajesAsync(object userState) {
            if ((this.getViajesOperationCompleted == null)) {
                this.getViajesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetViajesOperationCompleted);
            }
            this.InvokeAsync("getViajes", new object[0], this.getViajesOperationCompleted, userState);
        }
        
        private void OngetViajesOperationCompleted(object arg) {
            if ((this.getViajesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getViajesCompleted(this, new getViajesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getViajesCerrados", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getViajesCerrados() {
            object[] results = this.Invoke("getViajesCerrados", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getViajesCerradosAsync() {
            this.getViajesCerradosAsync(null);
        }
        
        /// <remarks/>
        public void getViajesCerradosAsync(object userState) {
            if ((this.getViajesCerradosOperationCompleted == null)) {
                this.getViajesCerradosOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetViajesCerradosOperationCompleted);
            }
            this.InvokeAsync("getViajesCerrados", new object[0], this.getViajesCerradosOperationCompleted, userState);
        }
        
        private void OngetViajesCerradosOperationCompleted(object arg) {
            if ((this.getViajesCerradosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getViajesCerradosCompleted(this, new getViajesCerradosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateRutaId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string updateRutaId(string rutaID, string viajeID) {
            object[] results = this.Invoke("updateRutaId", new object[] {
                        rutaID,
                        viajeID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void updateRutaIdAsync(string rutaID, string viajeID) {
            this.updateRutaIdAsync(rutaID, viajeID, null);
        }
        
        /// <remarks/>
        public void updateRutaIdAsync(string rutaID, string viajeID, object userState) {
            if ((this.updateRutaIdOperationCompleted == null)) {
                this.updateRutaIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateRutaIdOperationCompleted);
            }
            this.InvokeAsync("updateRutaId", new object[] {
                        rutaID,
                        viajeID}, this.updateRutaIdOperationCompleted, userState);
        }
        
        private void OnupdateRutaIdOperationCompleted(object arg) {
            if ((this.updateRutaIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateRutaIdCompleted(this, new updateRutaIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getViajesCompletedEventHandler(object sender, getViajesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getViajesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getViajesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getViajesCerradosCompletedEventHandler(object sender, getViajesCerradosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getViajesCerradosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getViajesCerradosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void updateRutaIdCompletedEventHandler(object sender, updateRutaIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateRutaIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateRutaIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591